### ISSUE TITLE
2주차 - TDD 시작 - 정창우

### ISSUE THREAD

**Issue by JungChangwoo** [GDSC-MYONGJI/22-23-TDD-Study#5]
#2
TDD란 무엇인지 알아보고, 현실적인 기능을 구현해보며
TDD의 흐름을 파악하고 알아가는 시간을 갖는다.

- [x]  암호 검사기 구현을 통해 TDD 경험해보기
- [ ] Chap 2의 내용을 개인 기술 블로그에 정리하기
- [x] Chap 2 내용을 보고 중요하다고 생각되는 부분에 해당하는 관련 문제를 만들고, Core Member에게 제출하기

**Comment by rladuswl** [comment]
main으로 모든 멤버의 프로젝트를 merge하기 때문에 본인 이름으로 디렉토리 생성 후, 그 안으로 모두 옮겨주세요!
위 과정 완료 후 pull request 해주시면 됩니다. 수고하셨습니다 :)
