### ISSUE TITLE
2주차 - TDD 시작 - 한규범

### ISSUE THREAD

**Issue by Qbeom0925** [GDSC-MYONGJI/22-23-TDD-Study#6]
#2
TDD란 무엇인지 알아보고, 현실적인 기능을 구현해보며
TDD의 흐름을 파악하고 알아가는 시간을 갖는다.

- [x]  암호 검사기 구현을 통해 TDD 경험해보기
- [x] Chap 2의 내용을 개인 기술 블로그에 정리하기
- [x] Chap 2 내용을 보고 중요하다고 생각되는 부분에 해당하는 관련 문제를 만들고, Core Member에게 제출하기

**Comment by hou27** [comment]
규범님!

개인이 발행한 이슈엔 마일스톤을 지정하지 않는게
추후 주된 이슈를 한눈에 보기 편할 것 같아서 설정하신 마일스톤을 없앴습니다!

감사합니다 :)

**Comment by Qbeom0925** [comment]
https://kbcoding.tistory.com/110
